export const defaultValues = {
  APPSHELL_HEADER_HEIGTH: 60,
  APPSHELL_NAVBAR_WIDTH: 300,
  NAVBAR_PARENT_LABEL_FONT_SIZE: 16,
  NAVBAR_PARENT_LABEL_FONT_WEIGHT: 500,
  NAVBAR_CHILD_LABEL_FONT_SIZE: 14,
  PUBLIC_LIVECHAT_PATHNAME: '/public/livechat',
};
