name: npm test

on:
  push:
    branches: ['development']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  npm_test_push:
    runs-on: ubuntu-latest
    environment: NpmTest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: npm run build
        env:
          DOCKER_BUILD: ${{ vars.DOCKER_BUILD }}
          SKIP_ENV_VALIDATION: ${{ vars.SKIP_ENV_VALIDATION }}
      - name: Run tests
        run: npm test
        env:
          DOCKER_BUILD: ${{ vars.DOCKER_BUILD }}
          SKIP_ENV_VALIDATION: ${{ vars.SKIP_ENV_VALIDATION }}
