name: npm test

on:
  push:
    branches: ['development']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'Production') || 'Development' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: npm run build
        env:
          DOCKER_BUILD: ${{ vars.DOCKER_BUILD }}
          SKIP_ENV_VALIDATION: ${{ vars.SKIP_ENV_VALIDATION }}
          PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
          PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
          PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
          PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
          NEXT_PUBLIC_PUSHER_APP_KEY: ${{ vars.NEXT_PUBLIC_PUSHER_APP_KEY }}
          NEXT_PUBLIC_PUSHER_APP_CLUSTER: ${{ vars.NEXT_PUBLIC_PUSHER_APP_CLUSTER }}
      - name: Run tests
        run: npm test
        env:
          DOCKER_BUILD: ${{ vars.DOCKER_BUILD }}
          SKIP_ENV_VALIDATION: ${{ vars.SKIP_ENV_VALIDATION }}
          PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
          PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
          PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
          PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
          NEXT_PUBLIC_PUSHER_APP_KEY: ${{ vars.NEXT_PUBLIC_PUSHER_APP_KEY }}
          NEXT_PUBLIC_PUSHER_APP_CLUSTER: ${{ vars.NEXT_PUBLIC_PUSHER_APP_CLUSTER }}
